[user_interface]
text_editor = "/usr/bin/nano"
default_protocol = "SFTP"
show_hidden_files = false
check_for_updates = true
prompt_on_file_replace = true
notifications = true
notification_threshold = 536870912

[remote]
ssh_config = "/Users/imaks/.ssh/config"

[remote.ssh_keys]
